//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 我救浪
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet_Detail
    {
        public int ProductID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<decimal> YearCost { get; set; }
        public Nullable<int> Space { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> AccompanyTimeWeek { get; set; }
        public Nullable<bool> IsLigation { get; set; }
        public string Description { get; set; }
    
        public virtual City City { get; set; }
        public virtual Color Color { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Product Product { get; set; }
        public virtual Size Size { get; set; }
    }
}
